### ISSUE TITLE
Tags for blog section

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/website#58]
### Problem
We already have many posts there and even more coming.  
Old posts are not visible and may never come to the eyes of the visitors.

### Solution
1) We can put “tag cloud” on the left of the page, so visitors can both see the overall picture and click on the tags to see related posts.
2) Also each post should have related tags, which should be visible (under the title) and work as urls to the corresponding list of related posts.

**Comment by deadit** [comment]
Already in production
