### ISSUE TITLE
Add Animation to "Getting started with Ergo" Button

### ISSUE THREAD

**Issue by pratul20** [ergoplatform/website#594]
Your website is very beautiful. But adding an animation to this button will make it more attractive.

**Comment by deadit** [comment]
@gaurav879 if you want you can take this task :)

**Comment by pratul20** [comment]
Can i work on this issue ?

**Comment by deadit** [comment]
> Can i work on this issue ?

Of course! Please, do it :)

**Comment by deadit** [comment]
@pratul20 Sorry, I think you don’t know css

**Comment by pratul20** [comment]
@deadit I have created the PR. Still learning CSS :)
