### ISSUE TITLE
noindex

### ISSUE THREAD

**Issue by glasgowm148** [ergoplatform/website#612]
Trying to crawl with a SEO tool and getting a noindex error.

![Screenshot 2021-11-04 at 23 28 35](https://user-images.githubusercontent.com/19927264/140434294-a8951861-e3e7-424e-bd3b-5b75746e28db.png)

**Comment by deadit** [comment]
DMed you. ergoplatform.org is just a redirect to the /en section this why it is have noindex meta tag.

**Comment by deadit** [comment]
Close for now
