### ISSUE TITLE
Probably typo in example source code

### ISSUE THREAD

**Issue by gagarin55** [ergoplatform/website#62]
In the blog post article.

Is it correct to compare tokens.size with TID ?
```
 buyerOut.tokens.size > TID 
```

https://github.com/ergoplatform/website/blame/master/content/en/blog/2020_04_29_flow_cards.md#L495

**Comment by aslesarenko** [comment]
@gagarin55 yes, it should be `buyerOut.tokens.size > TID.toInt`, with explicit type cast.
TID is an index of the token, not an id (despite the probably misleading name :))
BTW, this is actually described in the text.
